# Generated by Django 4.2.5 on 2023-12-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_articolo_options_alter_giornalista_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='visualizazioni',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
