# Generated by Django 4.2.5 on 2023-12-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_articolo_visualizazioni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articolo',
            name='visualizazioni',
            field=models.IntegerField(default=0),
        ),
    ]
