# Generated by Django 4.2.5 on 2023-12-01 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_articolo_visualizazioni'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articolo',
            old_name='visualizazioni',
            new_name='visualizzazioni',
        ),
    ]
